name: api-browser

on: [push, pull_request]
#on:
#  push:
#    branches: [ master ]
#  pull_request:
#    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run Tests
      env:
        CLIENT: test
        CSP_ALLOWED_HOSTS: "http://localhost:8081 ws://localhost:8081 http://localhost:9953 ws://localhost:9080 http://localhost:9080 ws://localhost:9081 http://localhost:9081 ws://localhost:9082 http://localhost:9082 ws://localhost:9084 http://localhost:9084"
        KUI_USE_PROXY: true
        MOCHA_RUN_TARGET: webpack
        NO_OPT: true
        TRAVIS_HOME: ${{ github.workspace }}
        TRAVIS_BUILD_DIR: ${{ github.workspace }}
        TRAVIS_JOB_ID: ${{ github.run_id }}
        TRAVIS_OS_NAME: linux
        TRAVIS_CPU_ARCH: amd64
        WEBPACK_CLIENT_URL: "http://localhost:9080/"
        WINDOW_WIDTH: 1400
        WINDOW_HEIGHT: 1050
        RUNNING_KUI_TEST: true
      run: ./tools/travis/install.sh && TEST_ROOT=packages/test TEST_SUITE_ROOT=node_modules/@kui-shell NYC_INSTRUMENTATION_DONE=true npm run compile && npx concurrently -n API1,API2 'npm run test1 api1' 'npm run test2 api2' && ./bin/switch-client.sh alternate >& /tmp/alt-switch.out && npm run kill || true; npm run kill:proxy || true && npm run watch:$MOCHA_RUN_TARGET >& /tmp/alt-watch.out && BOTTOM_INPUT_MODE=true npx concurrently -n BOTTOM 'npm run testv2 bottom-input'

